import { useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { useAuth } from '@/src/providers/AuthProvider';
import { supabase } from '@/src/lib/supabase';
import { colors, spacing } from '@/src/theme';

type ParsedActivity = { type: string; title: string; description?: string | null; metadata?: Record<string, unknown> };
export default function CaptureScreen() {
  const { session } = useAuth(); const [text, setText] = useState(''); const [items, setItems] = useState<ParsedActivity[]>([]); const [busy, setBusy] = useState(false); const [saving, setSaving] = useState(false);
  async function parse() { if (!text.trim() || busy) return; setBusy(true); const { data, error } = await supabase.functions.invoke('parse-log', { body: { text } }); setBusy(false); if (error) Alert.alert('Could not parse log', 'Check that the parse-log Edge Function is deployed.'); else setItems((data?.activities as ParsedActivity[] | undefined) ?? []); }
  async function confirm() { if (!session || !items.length) return; setSaving(true); const rows = items.filter(item => item.title?.trim()).map(item => ({ user_id: session.user.id, type: item.type || 'general', title: item.title.trim(), description: item.description?.trim() || null, metadata: item.metadata ?? {}, started_at: new Date().toISOString() })); const { error } = await supabase.from('activities').insert(rows); setSaving(false); if (error) Alert.alert('Could not save activities', error.message); else router.back(); }
  return <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.kicker}>QUICK CAPTURE</Text><Text style={styles.title}>Tell me what happened</Text><Text style={styles.subtitle}>Describe your day naturally. Review the extraction before it becomes part of your record.</Text><TextInput multiline autoFocus placeholder="Today I studied for 90 minutes and went to the gym..." placeholderTextColor={colors.muted} value={text} onChangeText={setText} style={styles.input} /><Pressable disabled={busy || !text.trim()} onPress={() => void parse()} style={[styles.button, (busy || !text.trim()) && styles.disabled]}><Text style={styles.buttonText}>{busy ? 'Reading...' : 'Preview activities'}</Text></Pressable>{items.length > 0 && <><Text style={styles.sectionTitle}>Review before saving</Text>{items.map((item, index) => <View style={styles.card} key={`${item.title}-${index}`}><Text style={styles.type}>{item.type.toUpperCase()}</Text><Text style={styles.itemTitle}>{item.title}</Text>{item.description && <Text style={styles.description}>{item.description}</Text>}<Text style={styles.metadata}>{JSON.stringify(item.metadata ?? {})}</Text></View>)}<Pressable disabled={saving} onPress={() => void confirm()} style={[styles.confirm, saving && styles.disabled]}><Text style={styles.buttonText}>{saving ? 'Saving...' : 'Confirm and save'}</Text></Pressable></>}</ScrollView></KeyboardAvoidingView>;
}

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.paper }, content: { padding: spacing.lg, paddingTop: 54, paddingBottom: 100 }, back: { color: colors.sageDark, fontSize: 16, fontWeight: '700', marginBottom: spacing.xl }, kicker: { color: colors.sageDark, fontSize: 12, fontWeight: '800', letterSpacing: 2 }, title: { color: colors.ink, fontSize: 34, fontWeight: '800', lineHeight: 40, marginTop: 6 }, subtitle: { color: colors.muted, fontSize: 16, lineHeight: 23, marginBottom: spacing.lg, marginTop: spacing.sm }, input: { backgroundColor: colors.card, borderColor: colors.line, borderRadius: 14, borderWidth: 1, color: colors.ink, fontSize: 16, minHeight: 150, padding: spacing.md, textAlignVertical: 'top' }, button: { alignItems: 'center', backgroundColor: colors.ink, borderRadius: 12, marginTop: spacing.md, padding: spacing.md }, disabled: { opacity: 0.45 }, buttonText: { color: colors.card, fontWeight: '800' }, sectionTitle: { color: colors.ink, fontSize: 20, fontWeight: '800', marginBottom: spacing.sm, marginTop: spacing.xl }, card: { backgroundColor: colors.card, borderRadius: 14, marginBottom: spacing.sm, padding: spacing.md }, type: { color: colors.coral, fontSize: 10, fontWeight: '800', letterSpacing: 1 }, itemTitle: { color: colors.ink, fontSize: 17, fontWeight: '800', marginTop: 6 }, description: { color: colors.muted, lineHeight: 20, marginTop: 5 }, metadata: { color: colors.muted, fontSize: 11, marginTop: spacing.sm }, confirm: { alignItems: 'center', backgroundColor: colors.sageDark, borderRadius: 12, marginTop: spacing.sm, padding: spacing.md } });
