import { useCallback, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text } from 'react-native';
import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import { router, useFocusEffect } from 'expo-router';
import { useAuth } from '@/src/providers/AuthProvider';
import { supabase } from '@/src/lib/supabase';
import { colors, spacing } from '@/src/theme';

export default function FinanceExportScreen() { const { session } = useAuth(); const [busy, setBusy] = useState(false); const exportCsv = async () => { if (!session) return; setBusy(true); try { const { data, error } = await supabase.from('transactions').select('transaction_date,transaction_type,amount,merchant,description,source').order('transaction_date', { ascending: true }); if (error) throw error; const header = 'date,type,amount,merchant,description,source'; const lines = (data ?? []).map(row => [row.transaction_date, row.transaction_type, row.amount, row.merchant, row.description, row.source].map(value => `"${String(value ?? '').replace(/"/g, '""')}"`).join(',')); const uri = `${FileSystem.cacheDirectory}personal-os-transactions.csv`; await FileSystem.writeAsStringAsync(uri, [header, ...lines].join('\n'), { encoding: FileSystem.EncodingType.UTF8 }); if (!(await Sharing.isAvailableAsync())) { Alert.alert('Export created', 'CSV backup saved in the app cache.'); return; } await Sharing.shareAsync(uri, { mimeType: 'text/csv', dialogTitle: 'Share Personal OS transactions' }); } catch (error) { Alert.alert('Could not export transactions', error instanceof Error ? error.message : 'Please try again.'); } finally { setBusy(false); } }; useFocusEffect(useCallback(() => { void exportCsv(); }, [])); return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.kicker}>FINANCE</Text><Text style={styles.title}>Export transactions</Text><Text style={styles.subtitle}>Create a CSV backup of your saved transactions and share it with another app.</Text><Pressable disabled={busy} onPress={() => void exportCsv()} style={[styles.button, busy && styles.disabled]}><Text style={styles.buttonText}>{busy ? 'Creating CSV...' : 'Create and share CSV'}</Text></Pressable></ScrollView>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.paper }, content: { padding: spacing.lg, paddingTop: 54, paddingBottom: 100 }, back: { color: colors.sageDark, fontSize: 16, fontWeight: '700', marginBottom: spacing.xl }, kicker: { color: colors.sageDark, fontSize: 12, fontWeight: '800', letterSpacing: 2 }, title: { color: colors.ink, fontSize: 34, fontWeight: '800', marginTop: 6 }, subtitle: { color: colors.muted, fontSize: 16, lineHeight: 23, marginTop: spacing.sm, marginBottom: spacing.xl }, button: { alignItems: 'center', backgroundColor: colors.ink, borderRadius: 12, padding: spacing.md }, disabled: { opacity: .45 }, buttonText: { color: colors.card, fontWeight: '800' } });
