import { useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import * as FileSystem from 'expo-file-system/legacy';
import { router } from 'expo-router';
import { useAuth } from '@/src/providers/AuthProvider';
import { supabase } from '@/src/lib/supabase';
import { colors, spacing } from '@/src/theme';
type Row = { amount: number; transaction_type: 'income' | 'expense'; merchant: string | null; transaction_date: string };
export default function FinanceImportScreen() { const { session } = useAuth(); const [filename, setFilename] = useState(''); const [password, setPassword] = useState(''); const [selectedUri, setSelectedUri] = useState(''); const [rows, setRows] = useState<Row[]>([]); const [busy, setBusy] = useState(false); const [saving, setSaving] = useState(false); const [isPdf, setIsPdf] = useState(false);
  async function pickFile() { const result = await DocumentPicker.getDocumentAsync({ type: ['text/csv', 'text/comma-separated-values', 'application/pdf', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-excel'], copyToCacheDirectory: true }); if (result.canceled) return; const file = result.assets[0]; const pdf = file.name.toLowerCase().endsWith('.pdf') || file.mimeType === 'application/pdf'; setFilename(file.name); setSelectedUri(file.uri); setIsPdf(pdf); setRows([]); }
  async function processFile() { if (!selectedUri) return; setBusy(true); try { if (isPdf || filename.toLowerCase().endsWith('.xlsx') || filename.toLowerCase().endsWith('.xls')) { const base64 = await FileSystem.readAsStringAsync(selectedUri, { encoding: FileSystem.EncodingType.Base64 }); const response = await supabase.functions.invoke('parse-statement', { body: { base64, filename, password: password || undefined } }); if (response.error) throw new Error(await getFunctionError(response.error)); setRows(normalizeRows(response.data?.transactions)); } else { setRows(parseCsv(await FileSystem.readAsStringAsync(selectedUri))); } } catch (error) { Alert.alert('Could not read statement', error instanceof Error ? error.message : 'Please choose a valid statement.'); } finally { setBusy(false); } }
  async function importRows() { if (!session || !rows.length) return; setSaving(true); const { error } = await supabase.from('transactions').insert(rows.map(row => ({ ...row, user_id: session.user.id, source: 'statement-import' }))); setSaving(false); if (error) Alert.alert('Could not import transactions', error.message); else router.back(); }
  return <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.kicker}>FINANCE</Text><Text style={styles.title}>Import a statement</Text><Text style={styles.subtitle}>Choose a CSV, Excel, or PDF. Protected files are processed temporarily and still require review.</Text><Pressable disabled={busy} onPress={() => void pickFile()} style={[styles.pick, busy && styles.disabled]}><Text style={styles.pickTitle}>Choose CSV, Excel, or PDF</Text><Text style={styles.pickBody}>{filename || 'No file selected'}</Text></Pressable>{selectedUri && <><TextInput secureTextEntry placeholder="Password (only if protected)" placeholderTextColor={colors.muted} value={password} onChangeText={setPassword} style={styles.input} /><Pressable disabled={busy} onPress={() => void processFile()} style={[styles.button, busy && styles.disabled]}><Text style={styles.buttonText}>{busy ? 'Reading statement...' : 'Preview transactions'}</Text></Pressable></>}{rows.length > 0 && <><Text style={styles.sectionTitle}>{rows.length} rows ready to review</Text>{rows.slice(0, 10).map((row, index) => <View style={styles.row} key={`${row.transaction_date}-${index}`}><View><Text style={styles.merchant}>{row.merchant || 'Uncategorized'}</Text><Text style={styles.date}>{row.transaction_date}</Text></View><Text style={row.transaction_type === 'income' ? styles.income : styles.expense}>{row.transaction_type === 'income' ? '+' : '-'} {row.amount.toFixed(2)}</Text></View>)}{rows.length > 10 && <Text style={styles.more}>Showing the first 10 rows.</Text>}<Pressable disabled={saving} onPress={() => void importRows()} style={[styles.confirm, saving && styles.disabled]}><Text style={styles.buttonText}>{saving ? 'Importing...' : 'Confirm import'}</Text></Pressable></>}</ScrollView></KeyboardAvoidingView>; }
async function getFunctionError(error: unknown): Promise<string> { const fallback = error instanceof Error ? error.message : 'The statement parser returned an error.'; const context = (error as { context?: Response }).context; if (!context) return fallback; try { const body = await context.clone().json() as { error?: string }; return body.error || fallback; } catch { return fallback; } }
function parseCsv(csv: string): Row[] { const lines = csv.split(/\r?\n/).filter(line => line.trim()); const start = /^\d{4}-\d{2}-\d{2}$/.test(parseCsvLine(lines[0] ?? '')[0]?.trim() ?? '') ? 0 : 1; return lines.slice(start).map(parseCsvLine).map(parts => { const date = parts[0]?.trim(); const amount = Number(parts[1]?.replace(/[^\d.-]/g, '')); const merchant = parts.slice(2).join(',').trim(); if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || !Number.isFinite(amount) || amount === 0) return null; return { amount: Math.abs(amount), transaction_type: amount < 0 ? 'expense' as const : 'income' as const, merchant: merchant || null, transaction_date: date }; }).filter((row): row is Row => row !== null); }
function parseCsvLine(line: string): string[] { const fields: string[] = []; let field = ''; let quoted = false; for (let index = 0; index < line.length; index += 1) { const character = line[index]; if (character === '"') { if (quoted && line[index + 1] === '"') { field += '"'; index += 1; } else quoted = !quoted; } else if (character === ',' && !quoted) { fields.push(field); field = ''; } else field += character; } fields.push(field); return fields; }
function normalizeRows(value: unknown): Row[] { if (!Array.isArray(value)) return []; return value.filter((item): item is Partial<Row> => typeof item === 'object' && item !== null).map(item => ({ amount: Math.abs(Number(item.amount) || 0), transaction_type: item.transaction_type === 'income' ? 'income' : 'expense', merchant: typeof item.merchant === 'string' ? item.merchant : null, transaction_date: typeof item.transaction_date === 'string' ? item.transaction_date : '' } as Row)).filter(row => row.amount > 0 && /^\d{4}-\d{2}-\d{2}$/.test(row.transaction_date)); }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.paper }, content: { padding: spacing.lg, paddingTop: 54, paddingBottom: 100 }, back: { color: colors.sageDark, fontSize: 16, fontWeight: '700', marginBottom: spacing.xl }, kicker: { color: colors.sageDark, fontSize: 12, fontWeight: '800', letterSpacing: 2 }, title: { color: colors.ink, fontSize: 34, fontWeight: '800', marginTop: 6 }, subtitle: { color: colors.muted, fontSize: 16, lineHeight: 23, marginTop: spacing.sm, marginBottom: spacing.lg }, pick: { backgroundColor: '#DCE8D8', borderRadius: 16, padding: spacing.lg }, pickTitle: { color: colors.ink, fontSize: 18, fontWeight: '800' }, pickBody: { color: colors.muted, marginTop: 6 }, input: { backgroundColor: colors.card, borderColor: colors.line, borderRadius: 12, borderWidth: 1, color: colors.ink, marginTop: spacing.md, padding: spacing.md }, button: { alignItems: 'center', backgroundColor: colors.ink, borderRadius: 12, marginTop: spacing.md, padding: spacing.md }, disabled: { opacity: 0.45 }, buttonText: { color: colors.card, fontWeight: '800' }, sectionTitle: { color: colors.ink, fontSize: 20, fontWeight: '800', marginBottom: spacing.sm, marginTop: spacing.xl }, row: { alignItems: 'center', backgroundColor: colors.card, borderBottomColor: colors.line, borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', paddingVertical: spacing.md }, merchant: { color: colors.ink, fontSize: 16, fontWeight: '700' }, date: { color: colors.muted, fontSize: 12, marginTop: 4 }, income: { color: colors.sageDark, fontWeight: '800' }, expense: { color: colors.coral, fontWeight: '800' }, more: { color: colors.muted, fontSize: 12, marginTop: spacing.sm }, confirm: { alignItems: 'center', backgroundColor: colors.sageDark, borderRadius: 12, marginTop: spacing.md, padding: spacing.md } });
