import { useCallback, useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { useAuth } from '@/src/providers/AuthProvider';
import { supabase } from '@/src/lib/supabase';
import { colors, spacing } from '@/src/theme';

type Note = { id: string; title: string; content: string; created_at: string };

export default function KnowledgeScreen() {
  const { session } = useAuth(); const [notes, setNotes] = useState<Note[]>([]); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [saving, setSaving] = useState(false);
  const loadNotes = useCallback(async () => { if (!session) return; const { data } = await supabase.from('notes').select('id,title,content,created_at').order('updated_at', { ascending: false }).limit(30); setNotes((data as Note[] | null) ?? []); }, [session]);
  useFocusEffect(useCallback(() => { void loadNotes(); }, [loadNotes]));
  async function saveNote() { if (!session || !title.trim() || !content.trim()) return; setSaving(true); const { data: note, error } = await supabase.from('notes').insert({ user_id: session.user.id, title: title.trim(), content: content.trim(), metadata: {} }).select('id').single(); setSaving(false); if (error) Alert.alert('Could not save note', error.message); else { if (note?.id) void supabase.functions.invoke('index-note', { body: { note_id: note.id } }); setTitle(''); setContent(''); void loadNotes(); } }
  return <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.kicker}>KNOWLEDGE</Text><Text style={styles.title}>Keep what matters</Text><Text style={styles.subtitle}>Notes, ideas, and things you want your future self to find.</Text><View style={styles.form}><Text style={styles.formTitle}>New note</Text><TextInput placeholder="Title" placeholderTextColor={colors.muted} value={title} onChangeText={setTitle} style={styles.input} /><TextInput multiline placeholder="Write something worth keeping..." placeholderTextColor={colors.muted} value={content} onChangeText={setContent} style={[styles.input, styles.noteInput]} /><Pressable disabled={saving || !title.trim() || !content.trim()} onPress={() => void saveNote()} style={[styles.button, (saving || !title.trim() || !content.trim()) && styles.disabled]}><Text style={styles.buttonText}>{saving ? 'Saving...' : 'Save note'}</Text></Pressable></View><Text style={styles.sectionTitle}>Recent notes</Text>{notes.length ? notes.map(note => <View style={styles.card} key={note.id}><Text style={styles.noteTitle}>{note.title}</Text><Text numberOfLines={3} style={styles.noteContent}>{note.content}</Text><Text style={styles.date}>{new Date(note.created_at).toLocaleDateString()}</Text></View>) : <View style={styles.empty}><Text style={styles.emptyTitle}>Your knowledge base is empty</Text><Text style={styles.noteContent}>Start with an idea, a lesson, or a decision you want to remember.</Text></View>}</ScrollView></KeyboardAvoidingView>;
}

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.paper }, content: { padding: spacing.lg, paddingTop: 54, paddingBottom: 100 }, back: { color: colors.sageDark, fontSize: 16, fontWeight: '700', marginBottom: spacing.xl }, kicker: { color: colors.sageDark, fontSize: 12, fontWeight: '800', letterSpacing: 2 }, title: { color: colors.ink, fontSize: 34, fontWeight: '800', marginTop: 6 }, subtitle: { color: colors.muted, fontSize: 16, lineHeight: 23, marginTop: spacing.sm, marginBottom: spacing.lg }, form: { backgroundColor: '#DCE8D8', borderRadius: 16, padding: spacing.md }, formTitle: { color: colors.ink, fontSize: 18, fontWeight: '800' }, input: { backgroundColor: colors.card, borderColor: colors.line, borderRadius: 11, borderWidth: 1, color: colors.ink, fontSize: 16, marginTop: spacing.sm, padding: spacing.md }, noteInput: { minHeight: 130, textAlignVertical: 'top' }, button: { alignItems: 'center', backgroundColor: colors.ink, borderRadius: 11, marginTop: spacing.sm, padding: spacing.md }, disabled: { opacity: 0.45 }, buttonText: { color: colors.card, fontWeight: '800' }, sectionTitle: { color: colors.ink, fontSize: 20, fontWeight: '800', marginBottom: spacing.sm, marginTop: spacing.xl }, card: { backgroundColor: colors.card, borderRadius: 14, marginBottom: spacing.sm, padding: spacing.md }, noteTitle: { color: colors.ink, fontSize: 17, fontWeight: '800' }, noteContent: { color: colors.muted, lineHeight: 20, marginTop: 6 }, date: { color: colors.muted, fontSize: 11, marginTop: spacing.sm }, empty: { backgroundColor: colors.card, borderRadius: 14, padding: spacing.lg }, emptyTitle: { color: colors.ink, fontSize: 17, fontWeight: '800' } });
