import { useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { useAuth } from '@/src/providers/AuthProvider';
import { supabase } from '@/src/lib/supabase';
import { colors, spacing } from '@/src/theme';

export default function LogScreen() {
  const { session } = useAuth(); const [type, setType] = useState('general'); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [saving, setSaving] = useState(false);
  async function save() { if (!session || !title.trim()) return; setSaving(true); const { error } = await supabase.from('activities').insert({ user_id: session.user.id, type, title: title.trim(), description: description.trim() || null, metadata: {}, started_at: new Date().toISOString() }); setSaving(false); if (error) Alert.alert('Could not save activity', error.message); else router.back(); }
  return <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.screen}><View style={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.kicker}>QUICK CAPTURE</Text><Text style={styles.title}>Log an activity</Text><Text style={styles.subtitle}>Keep it lightweight. You can add detail later.</Text><Text style={styles.label}>What kind of activity?</Text><View style={styles.types}>{['general', 'workout', 'learning', 'project'].map(option => <Pressable key={option} onPress={() => setType(option)} style={[styles.type, type === option && styles.selected]}><Text style={[styles.typeText, type === option && styles.selectedText]}>{option}</Text></Pressable>)}</View><Text style={styles.label}>Title</Text><TextInput autoFocus placeholder="e.g. Studied Random Forest" placeholderTextColor={colors.muted} value={title} onChangeText={setTitle} style={styles.input} /><Text style={styles.label}>Notes (optional)</Text><TextInput multiline placeholder="Anything worth remembering?" placeholderTextColor={colors.muted} value={description} onChangeText={setDescription} style={[styles.input, styles.notes]} /><Pressable disabled={saving || !title.trim()} onPress={() => void save()} style={[styles.button, (!title.trim() || saving) && styles.disabled]}><Text style={styles.buttonText}>{saving ? 'Saving...' : 'Save activity'}</Text></Pressable></View></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.paper }, content: { padding: spacing.lg, paddingTop: 54 }, back: { color: colors.sageDark, fontSize: 16, fontWeight: '700', marginBottom: spacing.xl }, kicker: { color: colors.sageDark, fontSize: 12, fontWeight: '800', letterSpacing: 2 }, title: { color: colors.ink, fontSize: 34, fontWeight: '800', marginTop: 6 }, subtitle: { color: colors.muted, fontSize: 16, lineHeight: 23, marginTop: spacing.sm, marginBottom: spacing.xl }, label: { color: colors.ink, fontSize: 14, fontWeight: '800', marginBottom: spacing.sm, marginTop: spacing.md }, types: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, type: { borderColor: colors.line, borderRadius: 20, borderWidth: 1, paddingHorizontal: spacing.md, paddingVertical: spacing.sm }, selected: { backgroundColor: colors.ink, borderColor: colors.ink }, typeText: { color: colors.muted, textTransform: 'capitalize' }, selectedText: { color: colors.card }, input: { backgroundColor: colors.card, borderColor: colors.line, borderRadius: 12, borderWidth: 1, color: colors.ink, fontSize: 16, padding: spacing.md }, notes: { minHeight: 100, textAlignVertical: 'top' }, button: { alignItems: 'center', backgroundColor: colors.ink, borderRadius: 12, marginTop: spacing.xl, padding: spacing.md }, disabled: { opacity: 0.45 }, buttonText: { color: colors.card, fontSize: 16, fontWeight: '800' } });
