import { useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { useAuth } from '@/src/providers/AuthProvider';
import { supabase } from '@/src/lib/supabase';
import { colors, spacing } from '@/src/theme';

export default function NutritionScreen() {
  const { session } = useAuth();
  const [meal, setMeal] = useState(''); const [calories, setCalories] = useState(''); const [protein, setProtein] = useState(''); const [notes, setNotes] = useState(''); const [saving, setSaving] = useState(false);
  async function saveMeal() { if (!session || !meal.trim()) return; setSaving(true); const { error } = await supabase.from('activities').insert({ user_id: session.user.id, type: 'nutrition', title: meal.trim(), description: notes.trim() || null, metadata: { calories: Number(calories) || 0, protein_grams: Number(protein) || 0 }, started_at: new Date().toISOString() }); setSaving(false); if (error) Alert.alert('Could not save meal', error.message); else router.back(); }
  return <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.screen}><View style={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.kicker}>NUTRITION</Text><Text style={styles.title}>Log a meal</Text><Text style={styles.subtitle}>Notice what fuels you without turning eating into a spreadsheet.</Text><Text style={styles.label}>Meal</Text><TextInput placeholder="e.g. Oats and eggs" placeholderTextColor={colors.muted} value={meal} onChangeText={setMeal} style={styles.input} /><View style={styles.metrics}><Metric label="Calories" value={calories} onChange={setCalories} /><Metric label="Protein (g)" value={protein} onChange={setProtein} /></View><Text style={styles.label}>Notes (optional)</Text><TextInput multiline placeholder="Anything worth remembering?" placeholderTextColor={colors.muted} value={notes} onChangeText={setNotes} style={[styles.input, styles.notes]} /><Pressable disabled={saving || !meal.trim()} onPress={() => void saveMeal()} style={[styles.button, (saving || !meal.trim()) && styles.disabled]}><Text style={styles.buttonText}>{saving ? 'Saving...' : 'Save meal'}</Text></Pressable></View></KeyboardAvoidingView>;
}

function Metric({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><TextInput keyboardType="number-pad" placeholder="0" placeholderTextColor={colors.muted} value={value} onChangeText={onChange} style={styles.metricInput} /></View>; }

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.paper }, content: { padding: spacing.lg, paddingTop: 54 }, back: { color: colors.sageDark, fontSize: 16, fontWeight: '700', marginBottom: spacing.xl }, kicker: { color: colors.sageDark, fontSize: 12, fontWeight: '800', letterSpacing: 2 }, title: { color: colors.ink, fontSize: 34, fontWeight: '800', marginTop: 6 }, subtitle: { color: colors.muted, fontSize: 16, lineHeight: 23, marginTop: spacing.sm, marginBottom: spacing.lg }, label: { color: colors.ink, fontSize: 14, fontWeight: '800', marginBottom: spacing.sm, marginTop: spacing.md }, input: { backgroundColor: colors.card, borderColor: colors.line, borderRadius: 12, borderWidth: 1, color: colors.ink, fontSize: 16, padding: spacing.md }, metrics: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.md }, metric: { flex: 1 }, metricLabel: { color: colors.muted, fontSize: 12, fontWeight: '700', marginBottom: 5 }, metricInput: { backgroundColor: colors.card, borderColor: colors.line, borderRadius: 12, borderWidth: 1, color: colors.ink, padding: spacing.md }, notes: { minHeight: 100, textAlignVertical: 'top' }, button: { alignItems: 'center', backgroundColor: colors.ink, borderRadius: 12, marginTop: spacing.xl, padding: spacing.md }, disabled: { opacity: 0.45 }, buttonText: { color: colors.card, fontSize: 16, fontWeight: '800' } });
